title: Pedro Flores
description:
  location: "Texas, USA"
  linkedin: www.linkedin.com/in/pedrol-flores
  <a href="https://www.linkedin.com/in/pedrol-flores/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
